### ISSUE TITLE
Cannot find twemoji

### ISSUE THREAD

**Issue by girotobial** [moritonal/mermaid-live#5]
OS: Pop!OS 20.04

Npm run build throws 
```sh
Error: cannot find module twemoji
```

after step:

```sh
emoji-to-icon --emoji 🐳 --size 48 --size 72 --size 96 --size 144 --size 168 --size 192 --padding '12%' --outDir ./icons
```

**Comment by girotobial** [comment]
Error not thrown if dev dependencies are installed.

**Comment by moritonal** [comment]
See that's interesting because that's a dependency within `emoji-to-icon`...

**Comment by girotobial** [comment]
I *think* it's because the ```run build``` command is dependant on ```emoji-to-icon``` because it uses it to generate an icon for the webpage. ```emoji-to-icon``` is only listed in the dev dependencies.
